### ISSUE TITLE
panic: repeated read on failed websocket connection

### ISSUE THREAD

**Issue by MarcLindenbach** [erroneousboat/slack-term#148]
I get the message `panic: repeated read on failed websocket connection` after slack-term has been running for a few minutes. I get this stack trace and the app crashes:
```
goroutine 90 [running]:───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
panic(0x7cb140, 0xc4203f9f20)                                                                                                                                 │
└───────/build/50b59b924ac145f7da290c3eaa618483-xenial/parts/go/build/src/runtime/panic.go:500 +0x1a1─────────────────────────────────────────────────────────┘
github.com/erroneousboat/slack-term/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc4205288c0, 0xffffffffffffffff, 0x0, 0xc420045e60, 0x404c7d, 0xc420045e60)
        /build/50b59b924ac145f7da290c3eaa618483-xenial/parts/slack-term/go/src/github.com/erroneousboat/slack-term/vendor/github.com/gorilla/websocket/conn.go:958 +0x16d
github.com/erroneousboat/slack-term/vendor/github.com/gorilla/websocket.(*Conn).ReadJSON(0xc4205288c0, 0x7f2300, 0xc420467f00, 0xa6b240, 0xc420425a00)
        /build/50b59b924ac145f7da290c3eaa618483-xenial/parts/slack-term/go/src/github.com/erroneousboat/slack-term/vendor/github.com/gorilla/websocket/json.go:45 +0x2f
github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc420114140)
        /build/50b59b924ac145f7da290c3eaa618483-xenial/parts/slack-term/go/src/github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack/websocket_managed_conn.go:288 +0xac
github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc420114140, 0xc42023ec00)
        /build/50b59b924ac145f7da290c3eaa618483-xenial/parts/slack-term/go/src/github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack/websocket_managed_conn.go:223 +0x57
created by github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack.(*RTM).ManageConnection
        /build/50b59b924ac145f7da290c3eaa618483-xenial/parts/slack-term/go/src/github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack/websocket_managed_conn.go:54 +0x297
```

I've installed the app through snap (https://github.com/snapcrafters/slack-term) and I am running Ubuntu 16.04.

**Comment by erroneousboat** [comment]
This will happen when you're losing connection to the internet.

In the off chance it can be something with a proxy, or firewall: https://github.com/erroneousboat/slack-term/issues/72
