### ISSUE TITLE
Simple install and minimal config seems to fail

### ISSUE THREAD

**Issue by pgray** [erroneousboat/slack-term#225]
I used the wiki page method for generating an OAuth token and put it in my `~/.slack-term` file.

Version: 4.1
Installation method: downloaded from release page + chmod
```
jq '.slack_token' .slack-term > /dev/null && echo "json ok"
json ok
```
output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a02b1]

goroutine 1 [running]:
github.com/erroneousboat/slack-term/service.NewSlackService(0xc420254000, 0x17, 0xc420254000, 0x0)
        /home/jp/go/src/github.com/erroneousboat/slack-term/service/slack.go:66 +0x2f1
github.com/erroneousboat/slack-term/context.CreateAppContext(0xc4201e4000, 0x17, 0x0, 0x0, 0x0, 0x8afcc4, 0x6, 0xc420242120, 0x116, 0x0, ...)
        /home/jp/go/src/github.com/erroneousboat/slack-term/context/context.go:77 +0xd3
main.main()
        /home/jp/go/src/github.com/erroneousboat/slack-term/main.go:102 +0x1b4
```

**Comment by btjanaka** [comment]
I think I may be experiencing a similar issue, except I just get
```
2019/12/15 15:42:00 unsupported block type
```
When I try to run `slack-term`

**Comment by erroneousboat** [comment]
Could you check out the master version and see if the problem persists?
