### ISSUE TITLE
Crash on first launch

### ISSUE THREAD

**Issue by crookedstorm** [erroneousboat/slack-term#36]
On the first launch on macOS Sierra, I got this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x161603]

goroutine 16 [running]:
panic(0x291780, 0xc42000a0b0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
golang.org/x/net/websocket.(*Conn).SetWriteDeadline(0x0, 0xecf9b4673, 0x329892cc, 0x431b60, 0xc420168380, 0x0)
    /home/jp/go/src/golang.org/x/net/websocket/websocket.go:269 +0x43
github.com/nlopes/slack.(*RTM).connect(0xc42008fc20, 0x1, 0x0, 0x0, 0x0, 0x0)
    /home/jp/go/src/github.com/nlopes/slack/websocket_managed_conn.go:94 +0x266
github.com/nlopes/slack.(*RTM).ManageConnection(0xc42008fc20)
    /home/jp/go/src/github.com/nlopes/slack/websocket_managed_conn.go:32 +0x44
created by github.com/erroneousboat/slack-term/src/service.NewSlackService
    /home/jp/go/src/github.com/erroneousboat/slack-term/src/service/slack.go:36 +0x42d
```

I just thought I'd report the crash.  On second launch all is well, and I cannot currently reproduce this.

**Comment by erroneousboat** [comment]
Happens to me sometimes as well. It probably has something to do with not able to start the connection to slack. I'll have a look, thanks.

**Comment by erroneousboat** [comment]
This should at least give a sensible error message when the connection to slack can't be established. However I'm not certain if this solves this particular problem, I'll have to see if it'll happen again in the future.

**Comment by henriquechehad** [comment]
same issue here

**Comment by erroneousboat** [comment]
@henriquechehad thanks for the heads up, still happens to me on occasion.

**Comment by erroneousboat** [comment]
Closed due to age
