### ISSUE TITLE
panic: runtime error: slice bounds out of range 

### ISSUE THREAD

**Issue by ghaabor** [erroneousboat/slack-term#47]
I kept pressing J and then I got this panic at some some point of the channels list.

**Comment by erroneousboat** [comment]
@ghaabor thanks, I'll have a look if I can reproduce it

**Comment by roukmoute** [comment]
I've many times this problem.
```
panic: runtime error: slice bounds out of range

goroutine 8 [running]:
panic(0x6900c0, 0xc42000a150)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/erroneousboat/go/src/github.com/nsf/termbox-go/api.go:330 +0x445
github.com/gizak/termui.hookTermboxEvt()
        /home/erroneousboat/go/src/github.com/gizak/termui/events.go:126 +0x34
created by github.com/gizak/termui.Init
        /home/erroneousboat/go/src/github.com/gizak/termui/render.go:28 +0xa4
```

**Comment by erroneousboat** [comment]
Reopening the issue, because it seems that with regular typing the problem is solved. However, I'm able to trigger it with scrolling the mouse wheel. I'll continue looking into this.
